# Junk testing notebook not the final model

In [1]:
import tensorflow as tf
import numpy as np

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
x = np.random.randn(13, 5)
print(x)

[[-0.64149669  0.69884429 -0.09923077  1.44719497 -0.39937688]
 [-1.57425213 -0.32263962  0.08185847  0.39051642  0.91326861]
 [ 0.37046333  0.64824388  0.3414695  -0.03425428  0.22262136]
 [ 0.34248392  1.63617858  1.25776522 -0.3087631   0.78926198]
 [-0.77981961 -0.07972376  1.07504756  0.96321429  0.33597874]
 [-0.53815735  2.39853366  0.65107899 -0.76856517 -0.53599128]
 [-1.57065663  0.69091467 -1.49945899  0.49739481  0.33475268]
 [ 0.36886721  0.93643886 -0.11605022 -0.46051834  0.10699717]
 [ 0.06518237 -0.57575168  0.07757798 -1.87890303 -0.08600087]
 [ 0.52027297 -0.31057518 -0.61645971 -0.06247435  0.3512117 ]
 [-0.68904986 -0.78242203 -0.90296344  0.28954674 -0.49460374]
 [ 1.0085212  -0.10302162  0.40371888  0.43977026 -0.28065346]
 [-0.69721952 -0.15639741  1.22729461  0.54655177 -0.21798084]]


In [5]:
emb = tf.constant(x)
print(emb)

Tensor("Const:0", shape=(13, 5), dtype=float64)


In [6]:
q = [1]
q_pl = tf.placeholder(tf.int32, [None], name = 'query')

In [7]:
lookup = tf.nn.embedding_lookup(emb, q_pl)

In [8]:
sess = tf.Session()

In [9]:
sess.run(lookup, feed_dict = {q_pl: q})

array([[-1.57425213, -0.32263962,  0.08185847,  0.39051642,  0.91326861]])

In [13]:
sess.run(tf.sigmoid([12., 0.]))

array([0.9999938, 0.5      ], dtype=float32)

In [15]:
batch_ = np.random.randn(10, 4)
print(batch_)
print(batch_[:, 1:])

[[-0.46150963  1.65220658 -1.22201059 -0.26363355]
 [ 0.22971067  1.33664605  0.11253774 -0.07970056]
 [ 1.92576167  0.73469331 -0.75642091  1.51890203]
 [ 1.20769575 -0.08556157 -0.06427001  0.36002096]
 [-1.68428291  0.24842158  1.15771564  0.52042367]
 [-1.14990415  0.03939468 -0.39121161 -0.47556889]
 [ 1.37515466  0.0112242  -0.40831684 -1.60524304]
 [ 1.60873132  1.29707674 -0.90152081 -0.57840124]
 [-0.51112579 -0.976894   -1.90939731  0.53125335]
 [-0.94501113  1.11559169 -0.61929821 -0.54978269]]
[[ 1.65220658 -1.22201059 -0.26363355]
 [ 1.33664605  0.11253774 -0.07970056]
 [ 0.73469331 -0.75642091  1.51890203]
 [-0.08556157 -0.06427001  0.36002096]
 [ 0.24842158  1.15771564  0.52042367]
 [ 0.03939468 -0.39121161 -0.47556889]
 [ 0.0112242  -0.40831684 -1.60524304]
 [ 1.29707674 -0.90152081 -0.57840124]
 [-0.976894   -1.90939731  0.53125335]
 [ 1.11559169 -0.61929821 -0.54978269]]


In [37]:
sequences = []
batch_size = 10
for i in range(batch_size):
    seq = np.random.randn(np.random.randint(1, 6)).astype(np.float32)
    sequences.append(seq)

sequences = np.array(sequences)
print(sequences)

[array([-1.5097468 ,  0.97187704, -1.1467037 ,  1.628563  ], dtype=float32)
 array([ 0.08486259, -1.4896799 ,  1.6080999 ], dtype=float32)
 array([-0.21923354, -1.9496495 , -2.5362346 , -0.98984426, -0.07178294],
      dtype=float32)
 array([-1.360168  , -0.18784778, -0.16101228, -0.8402991 ], dtype=float32)
 array([-0.86216503], dtype=float32)
 array([-1.0983992 ,  0.6750412 , -0.39504507], dtype=float32)
 array([ 0.63389575, -0.40742725,  0.6196666 ,  1.7046864 , -0.49599558],
      dtype=float32)
 array([-1.1983697 ,  0.3309764 ,  0.6203675 , -0.98709786,  0.61874163],
      dtype=float32)
 array([2.010768], dtype=float32)
 array([-0.39132604, -0.8241489 , -1.0844672 ,  0.8207169 ], dtype=float32)]


In [38]:
sequences.shape

(10,)

In [39]:
pad_id = 99.

In [40]:
seqlens = [i.shape[0] for i in sequences]
# print(seqlens)
for s in sequences:
    seq = np.append(arr = s, values = np.ones(5 - len(s),dtype = np.int32) * pad_id)
    print(seq)

[-1.50974679  0.97187704 -1.14670372  1.62856305 99.        ]
[ 8.48625898e-02 -1.48967993e+00  1.60809994e+00  9.90000000e+01
  9.90000000e+01]
[-0.21923354 -1.94964945 -2.53623462 -0.98984426 -0.07178294]
[-1.36016798 -0.18784778 -0.16101228 -0.84029913 99.        ]
[-0.86216503 99.         99.         99.         99.        ]
[-1.09839916  0.6750412  -0.39504507 99.         99.        ]
[ 0.63389575 -0.40742725  0.61966658  1.7046864  -0.49599558]
[-1.19836974  0.3309764   0.62036753 -0.98709786  0.61874163]
[ 2.01076794 99.         99.         99.         99.        ]
[-0.39132604 -0.82414889 -1.08446717  0.82071692 99.        ]


In [ ]:
inp = tf.placeholder(tf.int32, [None])

In [41]:
s

array([-0.39132604, -0.8241489 , -1.0844672 ,  0.8207169 ], dtype=float32)

In [42]:
x_l = [i*i for i in range(3)]
x_t = (i*i for i in range(3))

In [43]:
for i in x_l:
    print(i)
print()

for i in x_t:
    print(i)

0
1
4

0
1
4


In [45]:
for i in x_l:
    print(i)
print('here')

for i in x_t:
    print(i)

0
1
4
here


In [120]:
def add_padding(inp, pad_id, seqlen):
    '''
    Pad the input values to the required length
    Args:
        inp: input sequence with shape (batch_size, <variable>)
        pad_id: (int) ID for padding element
    Returns:
        (batch_size, seqlen)
        NOTE: zeros are added at the starting
    '''
    sequences = []
    for s in inp:
        if seqlen > len(s):
            s = np.append(arr = np.ones(seqlen - len(s)) * pad_id, values = s)
        if len(sequences) == 0:
            sequences = np.array([s])
            continue
        sequences = np.vstack((sequences, s[:seqlen]))
    return sequences

In [121]:
ab = add_padding(aa, 0, 6)

In [122]:
ab

array([[0., 0., 1., 2., 3., 4.],
       [0., 0., 1., 2., 3., 4.],
       [0., 0., 1., 2., 3., 4.]])

In [104]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])
z = np.array([1, 2, 3, 4])

aa = np.vstack([x, y, z])
print(aa)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [7]:
import numpy as np

In [88]:
class DatasetManager():
    def __init__(self, d1, d2, d3):
        self.d1 = d1
        self.d2 = d2
        self.d3 = d3
        
        assert d1.shape[0] == d2.shape[0] == d3.shape[0]
        
        self.s_idx = 0
        self.e_idx = 0
        
        self.num_iterations = 0
        
    def get_batch(self, batch_size):
        '''
        Get data of batch_size
        '''
        if self.s_idx + batch_size > len(self.d1):
            # print(self.s_idx)
            # this is the case for last turn
            batch_d1 = self.d1[self.s_idx:]
            batch_d2 = self.d2[self.s_idx:]
            batch_d3 = self.d3[self.s_idx:]
            
            # update values
            self.s_idx = 0
            self.e_idx = 0
            self.num_iterations += 1
            return batch_d1, batch_d2, batch_d3
        
        else:
            self.e_idx += batch_size
            batch_d1 = self.d1[self.s_idx: self.e_idx]
            batch_d2 = self.d2[self.s_idx: self.e_idx]
            batch_d3 = self.d3[self.s_idx: self.e_idx]
            self.s_idx += batch_size
            self.num_iterations += 1
            
            # checks
            if self.s_idx == len(self.d1):
                self.s_idx = 0
                self.e_idx = 0
            
            return batch_d1, batch_d2, batch_d3

In [89]:
d1 = np.random.rand(4, 5)
d2 = np.random.rand(4, 3)
d3 = np.random.rand(4, 6)

dm = DatasetManager(d1, d2, d3)

In [90]:
print(d1)
print(d2)
print(d3)

[[0.03574752 0.87439292 0.30221908 0.08502808 0.3685921 ]
 [0.33052081 0.21404975 0.89210862 0.09362656 0.88819515]
 [0.23424815 0.87307863 0.99709717 0.47424987 0.15143151]
 [0.65155443 0.5670377  0.6760352  0.03276259 0.04259237]]
[[0.22121048 0.57374088 0.62816716]
 [0.75685717 0.0146142  0.73698797]
 [0.61326372 0.03202296 0.99001436]
 [0.7016031  0.81621748 0.18414786]]
[[0.61509298 0.37458952 0.73702481 0.74902327 0.90045579 0.20822337]
 [0.35931915 0.12018324 0.93941825 0.14474288 0.1096412  0.1695401 ]
 [0.84256328 0.93674213 0.44490137 0.62517704 0.26774841 0.58643141]
 [0.40831214 0.81667463 0.80798518 0.57275245 0.72971093 0.0659975 ]]


In [91]:
print(dm.get_batch(3))

(array([[0.03574752, 0.87439292, 0.30221908, 0.08502808, 0.3685921 ],
       [0.33052081, 0.21404975, 0.89210862, 0.09362656, 0.88819515],
       [0.23424815, 0.87307863, 0.99709717, 0.47424987, 0.15143151]]), array([[0.22121048, 0.57374088, 0.62816716],
       [0.75685717, 0.0146142 , 0.73698797],
       [0.61326372, 0.03202296, 0.99001436]]), array([[0.61509298, 0.37458952, 0.73702481, 0.74902327, 0.90045579,
        0.20822337],
       [0.35931915, 0.12018324, 0.93941825, 0.14474288, 0.1096412 ,
        0.1695401 ],
       [0.84256328, 0.93674213, 0.44490137, 0.62517704, 0.26774841,
        0.58643141]]))


In [92]:
print(dm.get_batch(3))

(array([[0.65155443, 0.5670377 , 0.6760352 , 0.03276259, 0.04259237]]), array([[0.7016031 , 0.81621748, 0.18414786]]), array([[0.40831214, 0.81667463, 0.80798518, 0.57275245, 0.72971093,
        0.0659975 ]]))


In [93]:
print(dm.get_batch(1))

(array([[0.03574752, 0.87439292, 0.30221908, 0.08502808, 0.3685921 ]]), array([[0.22121048, 0.57374088, 0.62816716]]), array([[0.61509298, 0.37458952, 0.73702481, 0.74902327, 0.90045579,
        0.20822337]]))


In [94]:
print(dm.get_batch(1))

(array([[0.33052081, 0.21404975, 0.89210862, 0.09362656, 0.88819515]]), array([[0.75685717, 0.0146142 , 0.73698797]]), array([[0.35931915, 0.12018324, 0.93941825, 0.14474288, 0.1096412 ,
        0.1695401 ]]))


In [95]:
print(dm.get_batch(1))

(array([[0.23424815, 0.87307863, 0.99709717, 0.47424987, 0.15143151]]), array([[0.61326372, 0.03202296, 0.99001436]]), array([[0.84256328, 0.93674213, 0.44490137, 0.62517704, 0.26774841,
        0.58643141]]))


In [96]:
print(dm.get_batch(1))

(array([[0.65155443, 0.5670377 , 0.6760352 , 0.03276259, 0.04259237]]), array([[0.7016031 , 0.81621748, 0.18414786]]), array([[0.40831214, 0.81667463, 0.80798518, 0.57275245, 0.72971093,
        0.0659975 ]]))


In [97]:
print(dm.get_batch(1))

(array([[0.03574752, 0.87439292, 0.30221908, 0.08502808, 0.3685921 ]]), array([[0.22121048, 0.57374088, 0.62816716]]), array([[0.61509298, 0.37458952, 0.73702481, 0.74902327, 0.90045579,
        0.20822337]]))


In [98]:
print(dm.get_batch(1))

(array([[0.33052081, 0.21404975, 0.89210862, 0.09362656, 0.88819515]]), array([[0.75685717, 0.0146142 , 0.73698797]]), array([[0.35931915, 0.12018324, 0.93941825, 0.14474288, 0.1096412 ,
        0.1695401 ]]))


In [99]:
print(dm.get_batch(1))

(array([[0.23424815, 0.87307863, 0.99709717, 0.47424987, 0.15143151]]), array([[0.61326372, 0.03202296, 0.99001436]]), array([[0.84256328, 0.93674213, 0.44490137, 0.62517704, 0.26774841,
        0.58643141]]))


In [1]:
import numpy as np

In [4]:
x = np.random.random((12, 12))
print(type(x.astype(np.float32)))

<class 'numpy.ndarray'>


In [8]:
print(np.array(x).shape)

(12, 12)


In [9]:
x = np.array([1, 2, 3, 1, 3])
print(x.shape)
x = np.reshape(x, [-1, 1])
print(x.shape)

(5,)
(5, 1)
